# Generated by Django 5.0.3 on 2024-04-30 21:25

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_date_created'),
        ('main', '0003_alter_server_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('layout', models.CharField(choices=[('LE', 'Left'), ('RI', 'Right'), ('CE', 'Center')], max_length=128)),
                ('user_name', models.CharField(max_length=128)),
                ('user_pronouns', models.CharField(max_length=128)),
                ('text_info', models.JSONField(blank=True, default=dict)),
                ('link_info', models.JSONField(blank=True, default=dict)),
                ('background_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
