# Generated by Django 5.0.3 on 2024-07-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_card_background_color_remove_card_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='allow_create_accounts',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='server',
            name='allow_sign_in',
            field=models.BooleanField(default=1),
        ),
    ]
