# Generated by Django 5.0.3 on 2024-08-03 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_server_allow_create_accounts_server_allow_sign_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
