# Generated by Django 5.0.3 on 2024-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tempcard_alter_card_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcard',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
