# Generated by Django 5.0.3 on 2024-09-30 17:52

from django.db import migrations

def migrate_json_data(apps, schema_editor):
    Card = apps.get_model('main', 'Card')
    for obj in Card.objects.all():
        obj_json = obj.data
        
        if obj_json:
            obj_json["version"] = 4

            obj_json["font_style"] = "Simple"

            obj.data = obj_json
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_migrate_card_v2_to_v3'),
    ]

    operations = [
        migrations.RunPython(migrate_json_data)
    ]
