# Generated by Django 5.0.3 on 2024-04-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=256)),
                ('date_created', models.DateField(blank=True)),
            ],
        ),
    ]
