# Generated by Django 5.0.3 on 2024-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_date_created'),
        ('main', '0009_card_card_created_on_card_card_last_edited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.ManyToManyField(to='main.card'),
        ),
    ]
